#ifndef IBUS_DEVICES_H
#define IBUS_DEVICES_H

#define IBUS_DEVICE_RADIO 0x68
#define IBUS_DEVICE_CDPLAYER 0x18
#define IBUS_DEVICE_BOARD_MONITOR_BUTTONS 0xF0
#define IBUS_DEVICE_IKE 0x80
#define IBUS_DEVICE_MFW 0x50
#define IBUS_DEVICE_BROADCAST 0xFF

#endif